### ISSUE TITLE
TTN example

### ISSUE THREAD

**Issue by anbucher** [Xinyuan-LilyGO/T-Weigh#2]
Is it possible to provide a LORAWAN TTN example?

**Comment by FabTangi** [comment]
Is it possible to have an example using LMIC? 
Or to know the DIO Pins : 
https://github.com/matthijskooijman/arduino-lmic#dio-pins

**Comment by FabTangi** [comment]
Hello @anbucher you'll find here an example that may help you : 
https://github.com/FabTangi/PouezGwenan
